export enum authRoutes {
  home = 'home',
  barcode = 'barcode',
  myPage = 'myPage',
  singleOffer = 'singleOffer',
  spendOptions = 'spendOptions',
  aboutUs = 'aboutUs',
  news = 'news',
  parameters = 'parameters',
  changePassword = 'changePassword',
  getGift = 'getGift',
  orderDone = 'orderDone',
  PasswordChangingMessage = 'PasswordChangingMessage',
  PasswordChangingError = 'PasswordChangingError',
  changePin = 'changePin',
  singleNewsScreen = 'singleNewsScreen',
  partners = 'partners',
  singlePartners = 'singlePartners',
  aroundUs = 'aroundUs',
  searchScreen = 'searchScreen',
  singleMerchants = 'singleMerchants',
  allMerchants = 'allMerchants',
  spendOptions2 = 'spendOptions2',
  spendOptions3 = 'spendOptions3',
  searchResults = 'searchResults',
}

export enum notAuthRoutes {
  login = 'login',
  registration = 'registration',
  registrationDetails = 'registrationDetails',
  passwordInfo = 'passwordInfo',
  registrationDone = 'registrationDone',
  authScreen = 'authScreen',
  smsCode = 'smsCode',
  authPage = 'authPage',
  myCardInfo = 'myCardInfo',
  ResetPassStepOne = 'ResetPassStepOne',
  ResetPassStepTwo = 'ResetPassStepTwo',
}
